// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Import the escrow contract we built in Step 1
import "./LegalEscrow.sol";

contract LegalFactory {
    // Array to keep track of every escrow contract generated by the firm
    address[] public deployedEscrows;

    // Event to notify the Next.js frontend when a new case is successfully generated
    event EscrowCreated(address indexed escrowAddress, address indexed buyer, address indexed seller);

    // The function your Next.js app will call to generate a new settlement
    function createCase(
        address _buyer,
        address _seller,
        address _lawyer,
        uint256 _settlementAmount,
        string memory _documentHash
    ) external returns (address) {
        
        // This line deploys a brand new instance of the LegalEscrow contract
        LegalEscrow newEscrow = new LegalEscrow(
            _buyer,
            _seller,
            _lawyer,
            _settlementAmount,
            _documentHash
        );

        // Save the address of the newly created contract to our database
        deployedEscrows.push(address(newEscrow));

        // Emit the event so the frontend can redirect the user to the new contract's dashboard
        emit EscrowCreated(address(newEscrow), _buyer, _seller);

        // Return the address to the caller
        return address(newEscrow);
    }

    // Helper function for the Next.js frontend to fetch all cases for the lawyer's dashboard
    function getDeployedEscrows() external view returns (address[] memory) {
        return deployedEscrows;
    }
}